name: Dev Destroy

on:
  workflow_dispatch:
    inputs:
      folder:
        description: "Folder to destroy"
        required: true
        type: string

jobs:
  destroy:
    name: "Destroy Infrastructure"
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.1.0

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: latest
          token: ${{ secrets.GH_PAT }}

      - name: Destroy Terragrunt
        run: |
          echo "Folder ${{ github.event.inputs.folder }}"
          terragrunt destroy \
            --terragrunt-non-interractive \
            --auto-approve \
            --terragrunt-working-dir "infrastrcture/dev/eu-west-2/dev/${{ github.event.inputs.folder }}"
